ospf:
  process_id: 1
  router_id: 15.15.15.15
  redistribute:
    - protocol: connected
      route_map: loopback
  networks:
    - prefix: 172.20.12.0/24
      area: 0.0.0.0
    - prefix: 10.1.15.0/24
      area: 0.0.0.0
    - prefix: 10.2.15.0/24
      area: 0.0.0.0
