ospf:
  process_id: 1
  router_id: 11.11.11.11
  redistribute:
    - protocol: connected
      route_map: loopback
  networks:
    - prefix: 172.20.12.0/24
      area: 0.0.0.0
    - prefix: 10.1.11.0/24
      area: 0.0.0.0
    - prefix: 10.2.11.0/24
      area: 0.0.0.0
