route_maps:
  - name: BGP_DENY_DEFAULT_IN
    lines:
      - sequence: 10
        action: deny
        match:
          - ip address prefix-list DEFAULT_ROUTE
      - sequence: 20
        action: permit
        match:
          - ip address prefix-list ANY
  - name: BGP_PERMIT_ALL_IN
    lines:
      - sequence: 10
        action: permit
        match:
          - ip address prefix-list ANY
      - sequence: 20
        action: permit
        match:
          - ip address prefix-list DEFAULT_ROUTE
  - name: BGP_PERMIT_ALL_OUT
    lines:
      - sequence: 10
        action: permit
        match:
          - ip address prefix-list ANY
